resources:

- repo: self



pool:

  name: Hosted Ubuntu 1604

variables:
  BuildConfiguration: release
  RestoreBuildProjects: true
  BuildNumber: '1.0.$(Rev:r)'



steps:

- task: DotNetCoreCLI@2

  displayName: Restore

  inputs:

    command: restore

    projects: 'paket.install.sln'



- task: DotNetCoreCLI@2

  displayName: Build

  inputs:

    projects: 'paket.install.sln'

    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2

  displayName: Pack

  inputs:
    command: pack
    configuration: '$(BuildConfiguration)'
    packagesToPack: 'src/**/*.fsproj'
    packDirectory: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1

  displayName: 'Publish Artifact'

  inputs:

    PathtoPublish: '$(build.artifactstagingdirectory)'

  condition: succeededOrFailed()


- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NugetConnection'

    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))


